var json_AcidentesdeTrabalho_16 = {
"type": "FeatureCollection",
"name": "AcidentesdeTrabalho_16",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "OCORRÊNCIA": "os riscos da construção sem fiscalização: desastre na esquina de um beco; tres operarios saem feridos gravemente, um de 75 anos, um de 15 e um 12  (!!); jornal reivindica energica posição da fiscalizaçao pq coloca em risco a vida de operarios \"nem se per", "FONTE": "A Tribuna", "Link": "http:\/\/memoria.bn.br\/DocReader\/153931_00\/948", "End.Comple": "Ladeira Porto Geral, 48", "ID": "142", "End.Origin": "Ladeira Porto Geral, 7 [1908]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6332702, -23.5449061 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Carlos Manzone, 27 anos, morador desse endereço, carpinteiro, se feriu no trabalho", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/28731", "End.Comple": "Ladeira Porto Geral, 64", "ID": "203", "End.Origin": "Ladeira Porto Geral, 13 [1913]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6332158, -23.5447882 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Carlos sambiante, morador desse endereço, se machucou com açucar numa fabrica de doces", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/30403", "End.Comple": "Ladeira Porto Geral, 64", "ID": "204", "End.Origin": "Ladeira Porto Geral, 13A [1913]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.632922081340503, -23.5447050016997 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Lanza Felix, 44 anos, carpinteiro, morador desse endereço, caiu da escada no trabalho", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/28696", "End.Comple": "Ladeira Porto Geral, 64", "ID": "205", "End.Origin": "Ladeira Porto Geral, 13 [1913]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.633608867035797, -23.545024147521602 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Antonio de Oliveira, padeiro, machucou a mão enquanto trabalhava na padaria na mesma rua 34", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/30224", "End.Comple": "Rua do Glicério , 778", "ID": "208", "End.Origin": "Rua do Glicerio, 134 [1913]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6308485, -23.558945 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Carmelo Mastrocinni se machucou na mão com um formão enquanto trabalhava na oficina da Light", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/28268", "End.Comple": "Rua do Glicério, 8", "ID": "212", "End.Origin": "Rua do Glicerio, S\/N [1913]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.627211209663102, -23.552436899537899 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Henrique Arguida, trabalhando na Climaco Barbosa, feriu a mão esquerda", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/32506", "End.Comple": "Rua do Glicério , 782", "ID": "216", "End.Origin": "Rua do Glicerio, 137 [1913]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6308568, -23.55896 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "José de Azevedo,pedreiro, trabalhando na Republica, mahucou a mao com uma barra de ferro", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/30548", "End.Comple": "Rua do Glicério , 838", "ID": "217", "End.Origin": "Rua do Glicerio, 170 [1913]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6310736, -23.5594152 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "trabalhador antonio reis pisado por uma carroça enquanto removia areia", "FONTE": "O Estado de São Paulo", "Link": "https:\/\/acervo.estadao.com.br\/pagina\/#!\/19150523-13300-nac-0005-999-5-not\/busca\/aterrado+Gazometro", "End.Comple": "Parque D. Pedro II,", "ID": "259", "End.Origin": "Aterrado do Gazometro, S\/N [1915]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.629425343669098, -23.547299362991598 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "João Gomes, encanador, martelou o dedo enquanto trabalhava nessa oficina, mora na eugenio de lima", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/36539", "End.Comple": "Rua do Glicério , 794", "ID": "270", "End.Origin": "Rua do Glicerio, 146 [1915]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6309182, -23.5590673 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "José Hyppolito, funcionário de aguas e esgotos, foi trabalhar numa galeria nessa rua, levou uma lanterna e devido a um vazamento de gás de um cano ficou com graves queimaduras no rosto", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/36829", "End.Comple": "Rua do Glicério, 53", "ID": "271", "End.Origin": "Rua do Glicerio, S\/N [1915]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.627835823953497, -23.5530207511522 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "parda Maria Antonieta caiu na casa de seus patrões", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/41338", "End.Comple": "Rua do Glicério , 822", "ID": "290", "End.Origin": "Rua do Glicerio, 162 [1916]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6309971, -23.5592742 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Manuel Palido, operario das oficinas do estadão, se machucou no elevador fratura completa do braço esquerdo", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/42672", "End.Comple": "Rua do Glicério , 742", "ID": "301", "End.Origin": "Rua do Glicerio, 112 [1917]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6306944, -23.5586457 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Emilio Ruseo italiano lixeiro cortou dois dedos enquanto trabalhava", "FONTE": "O Combate", "Link": "http:\/\/memoria.bn.br\/DocReader\/830453\/2709", "End.Comple": "Rua do Glicério , 465", "ID": "312", "End.Origin": "Rua do Glicerio, 79 [1918]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6293527, -23.5566253 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Manuel de Araujo, empregado da Light, se bateu acidentalmente com o cabo da pá enquanto descarregava areia de um bonde de carga nessa rua", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/46291", "End.Comple": "Rua do Glicério, 8", "ID": "313", "End.Origin": "Rua do Glicerio, S\/N [1918]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.627786938545, -23.552573712844001 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "o preto João Malaquias foi atingido na cabeça por um tijolo caido de um andaime nessa rua", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/29772", "End.Comple": "Rua Dr. Bettencourt Rodrigues, 61", "ID": "437", "End.Origin": "Travessa do Mercado, S\/N [1913]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6310547, -23.5492641 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "João augusto carroceiro se machucou com a queda de uma pilha de sacos", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/37456", "End.Comple": "Rua Dr. Bettencourt Rodrigues, 80", "ID": "453", "End.Origin": "Travessa do Mercado, S\/N [1915]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6310062, -23.5489848 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Grave acidente de trabalho em obra", "FONTE": "O Commercio de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/227900\/22870", "End.Comple": "Rua vinte e cinco de março, 164", "ID": "486", "End.Origin": "Rua vinte e cinco de março, 40 [1909]", "PontoOrigi": "0", "CATEGORIA": "acidente de trabalho" }, "geometry": { "type": "Point", "coordinates": [ -46.6305866, -23.5480873 ] } }
]
}
