var json_InstituiesPblicas_9 = {
"type": "FeatureCollection",
"name": "InstituiesPblicas_9",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Comissão de saneamente da capital", "FONTE": "A Nação", "Link": "http:\/\/memoria.bn.br\/DocReader\/823279\/507", "End.Comple": "Rua vinte e cinco de março, 144", "End.Origin": "Rua vinte e cinco de março, 29 [1898]", "CATEGORIA": "Instituição pública" }, "geometry": { "type": "Point", "coordinates": [ -46.6306155, -23.5482609 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "4a repartiçào de policia do Braz", "FONTE": "Lavoura e Comércio", "Link": "http:\/\/memoria.bn.br\/DocReader\/817333\/67", "End.Comple": "Rua do Gasometro, 845", "End.Origin": "Rua do Gasometro, 158 [1898]", "CATEGORIA": "Instituição pública" }, "geometry": { "type": "Point", "coordinates": [ -46.617875200419299, -23.543022114039101 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Deposito Municipal do Braz, onde se estara vacinando as vacas todos os dias", "FONTE": "A Nação", "Link": "http:\/\/memoria.bn.br\/DocReader\/823279\/10", "End.Comple": "Rua do Gasometro, 781", "End.Origin": "Rua do Gasometro, 151A [1897]", "CATEGORIA": "Instituição pública" }, "geometry": { "type": "Point", "coordinates": [ -46.618807626900903, -23.542987403363799 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "no fim dessa rua ha um deposito(da sociedade protetora de animais) de caes vadios que passam a noite a uivar", "FONTE": "O Commercio de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/227900\/8065", "End.Comple": "Rua do Gasometro, 797", "End.Origin": "Rua do Gasometro, 154A [1899]", "CATEGORIA": "Instituição pública" }, "geometry": { "type": "Point", "coordinates": [ -46.6186135, -23.5431103 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "A UPA finalmente firmou acordo com a camara municipal para fazer cessar o revoltante metodo de extinçao de caes até então utilizado; os caes serào vendidos e texados e os que nào encontrarem donos vào ser sacrificados de forma moderna\/\/os caes ficam no d", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_05\/10985", "End.Comple": "Rua do Gasometro, 797", "End.Origin": "Rua do Gasometro, 154A [1899]", "CATEGORIA": "Instituição pública" }, "geometry": { "type": "Point", "coordinates": [ -46.618860328790497, -23.543522370843199 ] } }
]
}
