var json_Meretrcios_17 = {
"type": "FeatureCollection",
"name": "Meretrcios_17",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Maria Luiza da Conceição foi agredida em sua casa por um desconhecido que arremessou nela um despertador", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/32184", "End.Comple": "Rua Monsenhor Anacleto, 10", "End.Origin": "Rua Monsenhor Anacleto, 1 [1914]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.623470323692302, -23.545922557626199 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Francisca de Oliveira, depois de tomar pinga, tomou acido borico e gritou aos vizinhos, que acudiram\/\/mesma noticia no Correio, dá conta que Francisca era prostituta e bebia na cia de mulheres de vida igual", "FONTE": "O Commercio de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/227900\/21454", "End.Comple": "Rua Monsenhor Anacleto, 19", "End.Origin": "Rua Monsenhor Anacleto, 6 [1908]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.6233729928068, -23.546212756828599 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "parda Laura Pereira, de 23 anos, tentou suicidio tomando crysol por motivos desconhecidos", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/34380", "End.Comple": "Rua Monsenhor Anacleto, 19", "End.Origin": "Rua Monsenhor Anacleto, 6 [1914]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.6232764356972, -23.546608610753601 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "vende-se ai carne seca", "FONTE": "O Commercio de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/227900\/1249", "End.Comple": "Rua Monsenhor Anacleto, 22", "End.Origin": "Rua Monsenhor Anacleto, 7 [1894]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.6231778, -23.5462235 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Antonio Marcelino de Sousa, conhecido desordeiro, feriu com uma garrucha, por acidente, uma lavadeira; foi preso, depois, nesse endereço, casa de uma meretriz", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/10876", "End.Comple": "Rua Monsenhor Anacleto, 24", "End.Origin": "Rua Monsenhor Anacleto, 8 [1907]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.623476770805503, -23.544580167025298 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Maria Luppi fica na rua inventando varias historias possiveis pra um tiro que fora ouvido e reuniu curiosos, descobre-se que foi um acidente com arma de fogo apenas e, segundo o jornal, lincham a fofoqueira. O grande alarido e ajuntamento de gente é desc", "FONTE": "O Commercio de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/227900\/23510", "End.Comple": "Rua Monsenhor Anacleto, 29", "End.Origin": "Rua Monsenhor Anacleto, 10 [1909]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.623231906054997, -23.546072402572701 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "grande balburdia na casa onde residem varias mulheres de vida facil leva a um entrevero entre um cliente e um soldado rondante, cuja resistencia a prisão leva a seis tiros, soldado e paisano gravemente feridos", "FONTE": "O Commercio de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/227900\/23906", "End.Comple": "Rua Monsenhor Anacleto, 29", "End.Origin": "Rua Monsenhor Anacleto, 10 [1909]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.623101209499701, -23.5459822109339 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "a casa de tolerancia ainda existe ai onde Manuel Venancio, soldado do exercito, desentende-se com Maria do Carmo e trava grande desavença com soldados da guarda civica, e civis, até ser preso", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/38806", "End.Comple": "Rua Monsenhor Anacleto, 29", "End.Origin": "Rua Monsenhor Anacleto, 10 [1916]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.623105021625101, -23.546936987593501 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "uma preta, Maria do Carmo, recebeu dois tiros de revolver em uma casa de meetricio que funciona ai. Nem a vitima nem as companheiras souberam informar quem desferiu os tiros", "FONTE": "O Combate", "Link": "http:\/\/memoria.bn.br\/DocReader\/830453\/1066", "End.Comple": "Rua Monsenhor Anacleto, 34", "End.Origin": "Rua Monsenhor Anacleto, 13 [1918]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.6232364, -23.5462395 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Antonio Bella, ou Anthenor Bella foi preso em um bordel de infima classe nesse endereço, bebendo, tocando sanfona e violão e em cia de mulheres do bordel", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/36665", "End.Comple": "Rua Monsenhor Anacleto, 47", "End.Origin": "Rua Monsenhor Anacleto, 20 [1915]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.623477, -23.5463611 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Maria da Conceição tentou se matar tomando lysol", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/36477", "End.Comple": "Rua Monsenhor Anacleto, 47", "End.Origin": "Rua Monsenhor Anacleto, 20 [1915]", "CATEGORIA": "Tentativa de suícidio \/ estabelecimento - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.623946257819199, -23.546788942841498 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Maria Rosa do Carmo, se suicida tomando Lysol sem deixar carta nem pistas sobre o motivo", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/31333", "End.Comple": "Rua Monsenhor Anacleto, 92", "End.Origin": "Rua Monsenhor Anacleto, 39 [1913]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.623541750172599, -23.545662087886999 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Odorico de Carvalho, pintor, foi apunhalado pro um desconhecido quando saia da casa de tolerancia nesse endereço; cinco individuos se cercaram dele e um o agrediu", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/33840", "End.Comple": "Rua Monsenhor Anacleto, 97", "End.Origin": "Rua Monsenhor Anacleto, 41 [1914]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.6236681, -23.5457925 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Claudiano Rufino, soldado, teve uma desavença e agrediu Maria José Porto, prostituta e a agrediu covardemente", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/34955", "End.Comple": "Rua Monsenhor Anacleto, 28", "End.Origin": "Rua Monsenhor Anacleto, S\/N [1915]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.6231779, -23.5462233 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Francisco Vitalle e Archanjo Giuseppe foram presos em flagrante por caftens", "FONTE": "O Commercio de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/227900\/8223", "End.Comple": "Rua do Gasometro, 95", "End.Origin": "Rua do Gasometro, 17 [1900]", "CATEGORIA": "estabelecimentos - meretricio" }, "geometry": { "type": "Point", "coordinates": [ -46.6176549, -23.5429757 ] } }
]
}
