var json_Profissionaisliberais_12 = {
"type": "FeatureCollection",
"name": "Profissionaisliberais_12",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "OCORRÊNCIA": "G. Philadelpho medico especialista em molestia de criança mora ai", "FONTE": "A Nação", "Link": "http:\/\/memoria.bn.br\/DocReader\/823279\/50", "End.Comple": "Ladeira Porto Geral, 112", "End.Origin": "Ladeira Porto Geral, 23 [1897]", "CATEGORIA": "profissional liberal - médico" }, "geometry": { "type": "Point", "coordinates": [ -46.6328197, -23.5444843 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "adv Ortiz ajuda a vender hotel nessa cidade", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/39052", "End.Comple": "Rua do Glicério , 786", "End.Origin": "Rua do Glicerio, 142 [1916]", "CATEGORIA": "profissional liberal - advogado" }, "geometry": { "type": "Point", "coordinates": [ -46.6308764, -23.5589942 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Paulino Mota renomado cirurgião dentista abre gabinete nesse endereço", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/37328", "End.Comple": "Rua Dr. Bettencourt Rodrigues, 14", "End.Origin": "Travessa do Mercado, 1 [1915]", "CATEGORIA": "profissional liberal - dentista" }, "geometry": { "type": "Point", "coordinates": [ -46.6307381, -23.5495729 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Luiz da Gama anucia seus serviços de advogado, podendo ser procurado em sua residência. Anuncio de poesia logo a baixo", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_03\/164", "End.Comple": "Rua vinte e cinco de março, 376", "End.Origin": "Rua vinte e cinco de março, 99 [1870]", "CATEGORIA": "profissional liberal - advogado" }, "geometry": { "type": "Point", "coordinates": [ -46.6314845, -23.5464242 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Casa de saude e posto cirurgico do Sr. Botelho, inaugurada em 1884. Em 1894 é anunciada como de Tapajós e Fausto", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_05\/406", "End.Comple": "Rua do Gasometro, 43", "End.Origin": "Rua do Gasometro, 1 [1890]", "CATEGORIA": "profissional liberal - médico" }, "geometry": { "type": "Point", "coordinates": [ -46.625988, -23.54465 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "ensina-se bordado e faz-se roupas", "FONTE": "Jornal da Tarde", "Link": "http:\/\/memoria.bn.br\/DocReader\/713120\/2104", "End.Comple": "Rua do Gasometro, 56", "End.Origin": "Rua do Gasometro, 4 [1880]", "CATEGORIA": "profissional liberal - professor\/a" }, "geometry": { "type": "Point", "coordinates": [ -46.6177584, -23.5430078 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Dr. Archer de Castillo atende em sua residencia", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_05\/459", "End.Comple": "Rua do Gasometro, 135", "End.Origin": "Rua do Gasometro, 27 [1890]", "CATEGORIA": "profissional liberal - médico" }, "geometry": { "type": "Point", "coordinates": [ -46.617134645249301, -23.542768126218299 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Artidoro Pigatoo, professor de piano", "FONTE": "Gazeta Artistica", "Link": "http:\/\/memoria.bn.br\/DocReader\/103349\/443", "End.Comple": "Rua do Gasometro, 135", "End.Origin": "Rua do Gasometro, 27 [1913]", "CATEGORIA": "profissional liberal - professor\/a" }, "geometry": { "type": "Point", "coordinates": [ -46.617656641023601, -23.5426523254336 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "guarda-livros J.A. Thomaz Romeiro, chefe da contabilidade do Banco do Brasil", "FONTE": "Almanach da Provincia de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/829161\/1702", "End.Comple": "Rua do Gasometro, 148", "End.Origin": "Rua do Gasometro, 29 [1887]", "CATEGORIA": "profissional liberal - guarda-livros" }, "geometry": { "type": "Point", "coordinates": [ -46.6252002, -23.54475 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Francisca Bosi da aulas de bordado", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/633", "End.Comple": "Rua do Gasometro, 201", "End.Origin": "Rua do Gasometro, 37 [1900]", "CATEGORIA": "profissional liberal - professor\/a" }, "geometry": { "type": "Point", "coordinates": [ -46.6243975, -23.5442368 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "João Ferreira Machado, advogado", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_05\/24", "End.Comple": "Rua do Gasometro, 227", "End.Origin": "Rua do Gasometro, 41 [1890]", "CATEGORIA": "profissional liberal - advogado" }, "geometry": { "type": "Point", "coordinates": [ -46.6175396, -23.5429011 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "guarda-livros Dario Azevedo", "FONTE": "Almanach da Provincia de São Paulo", "Link": null, "End.Comple": "Rua do Gasometro, 465", "End.Origin": "Rua do Gasometro, 94 [1887]", "CATEGORIA": "profissional liberal - guarda-livros" }, "geometry": { "type": "Point", "coordinates": [ -46.6218361, -23.5438834 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "José Agostino da Silva Ferreira, empreiteiro de obras nesse endereço", "FONTE": "Almanach da Provincia de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/829161\/896", "End.Comple": "Rua do Gasometro, 518", "End.Origin": "Rua do Gasometro, 106 [1887]", "CATEGORIA": "profissional liberal - empreiteiro" }, "geometry": { "type": "Point", "coordinates": [ -46.621029, -23.5440991 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Dr. Alfredo Zuquim, médico", "FONTE": "A Nação", "Link": "http:\/\/memoria.bn.br\/DocReader\/823279\/6", "End.Comple": "Rua do Gasometro, 654", "End.Origin": "Rua do Gasometro, 122 [1897]", "CATEGORIA": "profissional liberal - médico" }, "geometry": { "type": "Point", "coordinates": [ -46.6198319, -23.543763 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Luiz Amato, professor de violino", "FONTE": "Gazeta Artistica", "Link": "http:\/\/memoria.bn.br\/DocReader\/103349\/443", "End.Comple": "Rua do Gasometro, 941", "End.Origin": "Rua do Gasometro, 190 [1913]", "CATEGORIA": "profissional liberal - professor\/a" }, "geometry": { "type": "Point", "coordinates": [ -46.617761727465698, -23.543084491192499 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "guarda-livros Luiz Drouet, guarda livros da Cia carris de ferro São Paulo", "FONTE": "Almanach da Provincia de São Paulo", "Link": null, "End.Comple": "Rua do Gasometro, 340", "End.Origin": "Rua do Gasometro, 63A [1887]", "CATEGORIA": "profissional liberal - guarda-livros" }, "geometry": { "type": "Point", "coordinates": [ -46.6175389, -23.5429007 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Dr. Antonio Luiz Pereira da Cunha atende em sua residencia nesse endereço", "FONTE": "GL'Italiani in San Paolo", "Link": "http:\/\/memoria.bn.br\/DocReader\/304395\/4", "End.Comple": "Rua do Gasometro, 701", "End.Origin": "Rua do Gasometro, S\/N [1888]", "CATEGORIA": "profissional liberal - advogado" }, "geometry": { "type": "Point", "coordinates": [ -46.617977097786699, -23.542948569112699 ] } }
]
}
