var json_ReuniesdeTrabalho_20 = {
"type": "FeatureCollection",
"name": "ReuniesdeTrabalho_20",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "OCORRÊNCIA": "reunião de greve na União dos trabalhadores gráficos, nesse endereço", "FONTE": "Correio Paulistano", "Link": "http:\/\/memoria.bn.br\/DocReader\/090972_06\/11154", "End.Comple": "Ladeira Porto Geral, 8", "ID": "134", "End.Origin": "Ladeira Porto Geral, 2 [1907]", "PontoOrigi": "0", "CATEGORIA": "reunião trabalhista" }, "geometry": { "type": "Point", "coordinates": [ -46.6339330019333, -23.545533387011101 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "a policia ontem entrou na sede da Liga dos pedreiros e ferreiros, mexeu numa gaveta e pegou cartas e atas de assembleia. \"sem comentários\"", "FONTE": "A Lanterna", "Link": "http:\/\/memoria.bn.br\/DocReader\/366153\/307", "End.Comple": "Ladeira Porto Geral, 8", "ID": "159", "End.Origin": "Ladeira Porto Geral, 2C [1911]", "PontoOrigi": "0", "CATEGORIA": "reunião trabalhista" }, "geometry": { "type": "Point", "coordinates": [ -46.633111379806103, -23.545281407495899 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "empregados de hoteis, bares, restaurantes e cafés fundaram uma associacào de classe com sede temporaria nesse endereço chamada \"A Internacional\"", "FONTE": "A Gazeta", "Link": "http:\/\/memoria.bn.br\/DocReader\/763900\/685", "End.Comple": "Ladeira Porto Geral, 8", "ID": "235", "End.Origin": "Ladeira Porto Geral, 2C [1914]", "PontoOrigi": "0", "CATEGORIA": "reunião trabalhista" }, "geometry": { "type": "Point", "coordinates": [ -46.633719612276103, -23.545240963451299 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "reunião dos sapateiros no salão Cesare Battisti", "FONTE": "O Combate", "Link": "http:\/\/memoria.bn.br\/DocReader\/830453\/57", "End.Comple": "Rua do Glicério , 826", "ID": "307", "End.Origin": "Rua do Glicerio, 164 [1917]", "PontoOrigi": "0", "CATEGORIA": "reunião trabalhista" }, "geometry": { "type": "Point", "coordinates": [ -46.6309918, -23.5593126 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "reunião operaria grevista de fabrica de calçados pra combinar como recebriam a recusa de sus reivindicaçòes", "FONTE": "O Combate", "Link": "http:\/\/memoria.bn.br\/DocReader\/830453\/61", "End.Comple": "Rua do Glicério , 826", "ID": "308", "End.Origin": "Rua do Glicerio, 164 [1917]", "PontoOrigi": "0", "CATEGORIA": "reunião trabalhista" }, "geometry": { "type": "Point", "coordinates": [ -46.631320065607603, -23.559062427312799 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "reunião ai dos trabalhadores de madeira com a finalidade de fundar uma liga", "FONTE": "O Combate", "Link": "http:\/\/memoria.bn.br\/DocReader\/830453\/2241", "End.Comple": "Rua do Gasometro, 267", "ID": "785", "End.Origin": "Rua do Gasometro, 49A [1919]", "PontoOrigi": "0", "CATEGORIA": "reunião trabalhista" }, "geometry": { "type": "Point", "coordinates": [ -46.6177273317576, -23.5424175878141 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "cocheiros, proibidos de circular desocupados pela região central da cidade do meio dia às 18h, entraram em greve, ajuntaram-se nessa rua, de onde foram \"apaziguados\" pela policia e seguiram causando disturbios dia afora em várias partes da cidade; a noit", "FONTE": "O Commercio de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/227900\/7661", "End.Comple": "Rua do Gasometro, 79", "ID": "811", "End.Origin": "Rua do Gasometro, S\/N [1899]", "PontoOrigi": "0", "CATEGORIA": "reunião trabalhista \/ casos de policia - perturbação da ordem" }, "geometry": { "type": "Point", "coordinates": [ -46.6255792, -23.5446001 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "Antonio Maffei e Alfredo Pietro foram à serralheria nessa rua, esquina com correa de andrade, para falar com os operarios dali sobre uma greve geral para reduçào de jornada. Ao que foram interpelados por Paulo rodrogues Teixeira \"que parece estar muito s", "FONTE": "O Commercio de São Paulo", "Link": "http:\/\/memoria.bn.br\/DocReader\/227900\/22960", "End.Comple": "Rua do Gasometro, 716", "ID": "813", "End.Origin": "Rua do Gasometro, S\/N [1909]", "PontoOrigi": "1", "CATEGORIA": "reunião trabalhista" }, "geometry": { "type": "Point", "coordinates": [ -46.6195358, -23.5436461 ] } },
{ "type": "Feature", "properties": { "OCORRÊNCIA": "delegados de varias comissões de operarios da Light se reuniram para discutir as varias violencias e perseguições perpetradas pela empresa contra os operários associados", "FONTE": "O Combate", "Link": "http:\/\/memoria.bn.br\/DocReader\/830453\/2547", "End.Comple": "Rua do Gasometro, 664", "ID": "816", "End.Origin": "Rua do Gasometro, S\/N [1919]", "PontoOrigi": "0", "CATEGORIA": "reunião trabalhista" }, "geometry": { "type": "Point", "coordinates": [ -46.619765, -23.5436829 ] } }
]
}
